package com.cheacloa.webscrapper;

public enum Category {
    ACCESSORIES,
    BABIES,
    BLAZERS,
    CARDIGANS_AND_JUMPERS,
    DRESSES_AND_JUMPSUITS,
    EXTRA_DISCOUNTS,
    JACKETS_AND_COATS,
    JEANS,
    KNITWEAR,
    LINGERIE,
    OTHERS,
    POLO_SHIRTS,
    SHOES,
    SHIRTS_AND_BLOUSES,
    SKIRTS_AND_SHORTS,
    SPORTS,
    SOCKS,
    SUITS,
    SWEATSHIRTS_HOODIES_AND_SWEATERS,
    SWIMWEAR,
    TRENDS,
    TSHIRTS_AND_TOPS,
    TROUSERS_AND_LEGGINGS,
    UNDERWEAR_AND_NIGHTWEAR
}
